### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Silvuz** [AntonelliLab/raxmlGUI#106]
Autogenerated report:
```json
{
  "message": "Cannot download \"https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.0-beta.6/raxmlGUI-Setup-2.0.0-beta.6.exe\", status 404: Not Found",
  "name": "Error",
  "stack": "Error: Cannot download \"https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.0-beta.6/raxmlGUI-Setup-2.0.0-beta.6.exe\", status 404: Not Found\n    at ClientRequest.<anonymous> (C:/Users/Ruben/AppData/Local/Programs/raxmlgui/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:248:26)\n    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:12)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 123 -p 123 -N 100 -m GTRGAMMA -O -n output.tre -s \"RAxML_output_concat.txt\" -w \"\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.5
Electron 7.1.10
win32 10.0.17763
Locale: pt-PT

**Comment by jtklein** [comment]
Fixed by keeping the name "raxmlGUI-Setup-version" for Windows
