### ISSUE TITLE
TypeError: a.map is not a function

### ISSUE THREAD

**Issue by nvpatin** [AntonelliLab/raxmlGUI#109]
I had a maximum likelihood analysis running for over 50 hours, all 100 bootstraps were completed and I was hopeful the phylogeny was close to being complete, when Raxml shut down with this error. To make matters worse, only two tree files were generated, RAxML_bootstrap.Woesearch_raxml.tre and RAxML_info.Woesearch_raxml.tre. The "bootstrap" tree does not actually appear to have bootstrap values in it (loaded it into iToL and have no option to add bootstraps). I ran this on MacOS Catalina v. 10.15.3 with two threads.

Are there any intermediate tree files possibly stored elsewhere?? And how do I prevent this happening in the future? I have run smaller jobs using the same parameters with RaxmlGUI recently, this was the largest one so far but I have never seen this error before.

Autogenerated report:
```json
{
  "name": "TypeError",
  "message": "a.map is not a function",
  "stack": "TypeError: a.map is not a function\n    at file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/main.b8a3aa04.chunk.js:1:19317\n    at file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:62475\n    at file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:62300\n    at ye (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:15894)\n    at e.track (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:20850)\n    at m (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:62277)\n    at c (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:62455)\n    at Ni (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:219294)\n    at ha (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:226378)\n    at fa (file:///Applications/raxmlGUI.app/Contents/Resources/app.asar/build/static/js/2.d04a97bd.chunk.js:1:226197)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3 -T 2 -f a -x 327 -p 259 -N 100 -m PROTGAMMABLOSUM62 -O -o Nitrosopumilus_maritimus_SCM1 -n 1.tre -s /Users/npatin3/Dropbox (GaTech)/Blue Holes/Data/Phylogenomics/040120/concatenated-proteins_edited.fa.reduced -w /Users/npatin3/Dropbox (GaTech)/Blue Holes/Data/Phylogenomics/040120",
  "stdout": "[13146 more characters]...nds\nThe file /Users/npatin3/Dropbox (GaTech)/Blue Holes/Data/Phylogenomics/040120/RAxML_info.Woesearch_raxml.tre RAxML wants to open for writing or appending can not be opened [mode: ab], exiting ...\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.2
Electron 6.0.2
darwin 19.3.0
Locale: en-US

**Comment by danieledler** [comment]
Hi,

The files written should all be in the output directory you have selected, so if you don't find any result files there from the big run I'm sorry they were not written completely for some reason that I don't know yet. I see you are using a rather old version of the raxmlGUI though, 2.0.0-beta.2. I would first recommend you to update to the latest version, and then maybe try running with a subset of the data to make it finish quicker to see if that works?
