### ISSUE TITLE
Error: parsing file

### ISSUE THREAD

**Issue by clif7050** [AntonelliLab/raxmlGUI#169]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Error parsing file /Users/Cliffy/Desktop/NHE tree  - Corals/regions.fst: 'No taxon line found before line 1 ('\t>A.yongei_NHE').",
  "stack": "Error: Error parsing file /Users/Cliffy/Desktop/NHE tree  - Corals/regions.fst: 'No taxon line found before line 1 ('\t>A.yongei_NHE').\n    at fastaParser_parse$0 (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:15079)\n    at Interface.<anonymous> (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:15842)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /Users/Cliffy/Desktop/NHE tree  - Corals/RAxML_regions_concat.txt --model  --prefix /Users/Cliffy/Desktop/NHE tree  - Corals/regions --seed 123 --bs-metric tbe --tree rand{1} --bs-trees 100",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.0
Electron 10.1.1
darwin 19.6.0
Locale: en-US

**Comment by jtklein** [comment]
Hello! Thank you for your report!

From the error message I can see that the app couldn't parse your fasta file. Could you provide this file? Then we can try to figure out what was the problem.

Thanks again!
Johannes
