### ISSUE TITLE
Change from generic to specific error message for unequal length alignment

### ISSUE THREAD

**Issue by Inom92** [AntonelliLab/raxmlGUI#192]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Error parsing file D:\\Hedyasrum L\\Hedysarum yangi\\Maqola\\Phylogeny\\jModelTest\\all species.fas: Sequence 'Hedysarum brachypterumHedsyarum' have different length (1797) than previous taxons (1843).",
  "stack": "Error: Error parsing file D:/Hedyasrum L/Hedysarum yangi/Maqola/Phylogeny/jModelTest/all species.fas: Sequence 'Hedysarum brachypterumHedsyarum' have different length (1797) than previous taxons (1843).\n    at fastaParser_parse$0 (C:/Users/ИНОМ/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:16712)\n    at Interface.<anonymous> (C:/Users/ИНОМ/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:17290)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 87333 -p 87333 -N 100 -m GTRGAMMA -O -n all_species.tre -s \"D:\\Hedyasrum L\\Hedysarum yangi\\Maqola\\Phylogeny\\jModelTest\\RAxML_all_species_concat.txt\" -w \"D:\\Hedyasrum L\\Hedysarum yangi\\Maqola\\Phylogeny\\jModelTest\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.5
Electron 12.0.7
win32 10.0.10586
Locale: ru

**Comment by jtklein** [comment]
Thank you for your report!

You have to make sure that in your alignment all sequences have the same length.

But I will also consider adding a more detailed explanation to the GUI for this case.
